# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /blobstorage
EXPOSE 80

# copy csproj and restore as distinct layers
COPY ./Request/Request.csproj ./
RUN dotnet restore

# copy everything else and build app
WORKDIR /blobstorage
COPY ./Request/ ./Request/

WORKDIR /blobstorage/Request
RUN dotnet publish -c release -o Request -r ubuntu.18.04-x64
# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=build / ./

WORKDIR /blobstorage/Request
ENTRYPOINT ["dotnet", "bin/release/net6.0/ubuntu.18.04-x64/Request.dll"]