apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: fwDaysKeyVaultDemo
  - name: spnTenantId
    value: "336eb426-4877-4e1d-98c3-87f51d33b11a"
  - name: spnClientId
    value: "949aa694-991b-4919-ac64-4ad9217772f4"
  - name: spnCertificateFile
    value : "./Components/fwdayskey.pfx"
