# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /cosmosdb
EXPOSE 80

# copy csproj and restore as distinct layers
WORKDIR /cosmosdb/Query
COPY ./Query/Query.csproj ./
RUN dotnet restore

# copy everything else and build app
WORKDIR /cosmosdb
COPY ./Query/ ./Query/

WORKDIR /cosmosdb/Query
RUN dotnet publish -c release -o Query -r ubuntu.18.04-x64

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=build / ./
WORKDIR /cosmosdb/Query
ENTRYPOINT ["dotnet", "bin/release/net6.0/ubuntu.18.04-x64/Query.dll"]